connect_mysql:connect_mysql.c
	gcc -g -c connect_mysql.c -I /home/guosong/mysql5627/include -L /home/guosong/mysql5627/lib -lmysqlclient
	gcc -o connect_mysql connect_mysql.o

clean:
	rm -rf *.o
	rm -rf connect_mysql
